name: flutter_quiz
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'
dependencies:
  flutter:
    sdk: flutter

  curved_navigation_bar: ^1.0.3
  youtube_player_flutter: ^8.1.1
  shared_preferences: ^2.0.15
  font_awesome_flutter: ^10.3.0
  audioplayers: ^0.20.1
  syncfusion_flutter_gauges: ^20.3.59
  confetti: ^0.6.0
  cupertino_icons: ^1.0.2
  url_launcher: ^6.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/